services:
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=Y
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - seq-data:/data

volumes:
  seq-data:
